### ISSUE TITLE
Tampilkan pesan jika not found

### ISSUE THREAD

**Issue by superpikar** [Vandemonica/internship-pikarlabs#1]
Untuk : 
- php-logic/array-3.php
- php-logic/array-4.php
- php-logic/array-5.php

jika tidak ditemukan, tampilkan pesan

**Comment by Vandemonica** [comment]
![Screenshot (29)](https://user-images.githubusercontent.com/66208743/104116682-71b1d880-534d-11eb-8b82-b9ff3b1ecb41.png)
![Screenshot (30)](https://user-images.githubusercontent.com/66208743/104116684-72e30580-534d-11eb-8ba5-11a231be647e.png)
![Screenshot (31)](https://user-images.githubusercontent.com/66208743/104116686-737b9c00-534d-11eb-97f4-6bf68c78fcae.png)
