### ISSUE TITLE
Echo lebih baik di akhir agar lebih mudah dibaca kodenya

### ISSUE THREAD

**Issue by superpikar** [Vandemonica/internship-pikarlabs#2]
Untuk 
- phplogic/string-1.php
- phplogic/string-2.php

Saat ini echo di dalam looping, menurutku agak susah dibacanya lebih baik ditaruh di akhir looping saja. 

instead
```
for(........){
    if(....){
        echo (...);
    }
    //selain dari itu($slasher sama dengan atau lebih besar $len), maka..
    else{
        echo(...);
    }
}
```

ubah jadi
```
$result='';
for(........){
    if(....){
        $result .= ...;
    }
    //selain dari itu($slasher sama dengan atau lebih besar $len), maka..
    else{
        $result .= ...;
    }
}
echo $result;
```

**Comment by Vandemonica** [comment]
![Screenshot (32)](https://user-images.githubusercontent.com/66208743/104116765-306df880-534e-11eb-8732-c96ae50bcf9d.png)
![Screenshot (33)](https://user-images.githubusercontent.com/66208743/104116767-32d05280-534e-11eb-9d04-24904f915d61.png)
