### ISSUE TITLE
layout php-request tidak sesuai instruksi

### ISSUE THREAD

**Issue by superpikar** [Vandemonica/internship-pikarlabs#3]
kurang menampilkan pesan pencarian

dan tampilkan pesan jika data tidak ditemukan 

![image](https://user-images.githubusercontent.com/2832280/104086982-fe499180-528e-11eb-8aa7-e1a2dd12b786.png)
![image](https://user-images.githubusercontent.com/2832280/104087009-22a56e00-528f-11eb-998d-fb1399cd30c7.png)

**Comment by Vandemonica** [comment]
![Screenshot (34)](https://user-images.githubusercontent.com/66208743/104116809-8b9feb00-534e-11eb-960b-aa040df4450e.png)
