### ISSUE TITLE
code untuk layout array-request-2.php

### ISSUE THREAD

**Issue by superpikar** [Vandemonica/internship-pikarlabs#4]
ketika menampilkan form dan table tidak perlu if-else, cukup cek jika ada param cari atau go maka : 
- tampilkan pesan pencarian
- array yg dilooping dalam table ambil dari output cariSiswa($keyword, $listSiswa);

![image](https://user-images.githubusercontent.com/2832280/104087069-af502c00-528f-11eb-874c-bbd08c95dab6.png)

**Comment by Vandemonica** [comment]
![Screenshot (35)](https://user-images.githubusercontent.com/66208743/104116833-bdb14d00-534e-11eb-9054-745b88c70642.png)
![Screenshot (36)](https://user-images.githubusercontent.com/66208743/104116834-bee27a00-534e-11eb-9989-58599dec17c9.png)
