### ISSUE TITLE
muncul error jika pencarian empty string

### ISSUE THREAD

**Issue by superpikar** [Vandemonica/internship-pikarlabs#5]
jika empty string maka tampilkan data awal

![image](https://user-images.githubusercontent.com/2832280/104087195-8b411a80-5290-11eb-9c2e-4bbd7f52c9b0.png)

**Comment by Vandemonica** [comment]
![Screenshot (37)](https://user-images.githubusercontent.com/66208743/104116865-fbae7100-534e-11eb-8538-30b0b305754c.png)
![Screenshot (38)](https://user-images.githubusercontent.com/66208743/104116868-fd783480-534e-11eb-9764-3f20975b3aa7.png)
![Screenshot (39)](https://user-images.githubusercontent.com/66208743/104116869-fe10cb00-534e-11eb-8895-1e573e381f44.png)
