### ISSUE TITLE
same include in v1.php and v2.php

### ISSUE THREAD

**Issue by renaldypermana** [Vandemonica/internship-pikarlabs#6]
![image](https://user-images.githubusercontent.com/37020760/106229599-7bc64900-6220-11eb-8347-df79888e3868.png)

Solusi

ganti  posisi include navbar ke layout.twig (taruh kode sebelum block content),

**Comment by renaldypermana** [comment]
Footer dan header juga sama , jadi benerin sekalian ya

**Comment by Vandemonica** [comment]
Navbar sekarang diinclude pada _layout.twig
![Screenshot (70)](https://user-images.githubusercontent.com/66208743/106256254-9c58c800-624d-11eb-84c1-d07decda3632.png)

Also sekarang navbar punya struktur array sendiri(agar section tidak ikut terpanggil di index dan portfolio maka saya kosongi index array navbar ke 1)
![Screenshot (69)](https://user-images.githubusercontent.com/66208743/106256468-e6da4480-624d-11eb-8099-61bc052e3ca1.png)
